owner: dixneuf19
repo: upptime
user-agent: dixneuf19
sites:
  - name: Dixneuf19 website
    url: https://www.dixneuf19.me
  - name: Radio France Open API
    url: $RADIO_FRANCE_API_URL_WITH_TOKEN
  - name: loudnaround.org
    url: https://loudnaround.org
  - name: mangococo.fr
    url: https://www.mangococo.fr/
  - name: This Upptime website
    url: https://upptime.dixneuf19.me
notifications: []
  # - type: slack
  #   channel: C016QTU9S9Y
assignees:
  - dixneuf19
status-website:
  cname: upptime.dixneuf19.me
  logoUrl: https://raw.githubusercontent.com/dixneuf19/upptime/assets/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: An uptime tracker for some services I care about
